---
title: "Anomia"
author: "Camilo Riquelme - Jaime Salinas - Isidora Toledo"
date: '2022-06-16'
output: pdf_document
toc: true
---

#### Universidad Alberto Hurtado
#### Carrera: Sociología
#### Profesora: Maria Constanza Ayala Reyes
#### Ayudante: Clemente Silva


```{r paquetes, include=FALSE}
pacman::p_load(haven, tidyverse, sjmisc, sjPlot, kableExtra, modeest)
```

```{r datos, include=FALSE}
data = read_dta("input/data/base_85.dta")
```

```{r procesamiento datos, include=FALSE}
data_proc = data%>% 
  mutate(iden_pol = case_when(iden_pol_2 >= 1 & iden_pol_2 <= 2 ~"Izquierda",
                              iden_pol_2 >= 3 & iden_pol_2 <= 4 ~"Centro Izquierda",
                              iden_pol_2 >= 5 & iden_pol_2 <= 6 ~"Centro",
                              iden_pol_2 >= 7 & iden_pol_2 <= 8 ~"Centro Derecha",
                              iden_pol_2 >= 9 & iden_pol_2 <= 10 ~"Derecha",
                              TRUE~NA_character_),
         confianza = case_when(confianza_6_j==1 ~"Mucha Confianza", 
                               confianza_6_j==2 ~"Bastante Confianza",
                               confianza_6_j==3 ~"Poca Confianza",
                               confianza_6_j==4 ~"Nada de Confianza",
                               TRUE~NA_character_),
         conf_dummy = case_when(confianza_6_j >=1 & confianza_6_j<=2 ~"Confianza",
                                confianza_6_j >=3 & confianza_6_j<=4 ~"Desconfianza"),
         edad_tr = case_when(edad<=29 ~"Jovenes",
                          edad>=30 & edad<=59 ~"Adultos/as",
                          edad>=60 ~"Adulto/a Mayor",
                          TRUE~NA_character_),
         sexo = case_when(sexo==1 ~"Hombre", sexo==2 ~"Mujer"))%>%
  select(sexo, edad, edad_tr, iden_pol, confianza, conf_dummy)

data_proc$iden_pol = factor(data_proc$iden_pol, levels = c(
  "Izquierda", "Centro Izquierda", "Centro", "Centro Derecha", "Derecha"))
data_proc$confianza = factor(data_proc$confianza, levels = c(
  "Mucha Confianza", "Bastante Confianza", "Poca Confianza", "Nada de Confianza"))
```

#Tablas y Graficos

```{r Univariado, echo=FALSE}
plot_frq(data_proc$conf_dummy,
         title = "Distribucion Niveles de Confianza", geom.colors = "purple")
```



```{r Bivariado 1, echo=FALSE}
plot_grpfrq(data_proc$iden_pol, data_proc$confianza,
            title = "Distribucion de niveles de Confianza según Identificacion Politica",
            coord.flip = T, show.n = F)
```



```{r Bivariado 2, echo=FALSE}
plot_xtab(data_proc$confianza, data_proc$iden_pol, 
          title = "Grado de Confianza de cada Identificacion Politica", 
          show.n = F, coord.flip = T)
```



```{r Bivariado 3, echo=FALSE}
plot_xtab(data_proc$conf_dummy, data_proc$iden_pol, 
          title = "Confianza/Desconfianza de cada Identificacion Politica", 
          geom.colors = "pink", 
          show.n = F, 
          coord.flip = T)
```



```{r Bivariado 4, echo=FALSE}
plot_xtab(data_proc$conf_dummy, data_proc$sexo,
          title = "Grado de Confianza según sexo",
          geom.colors = "purple",
          show.n = F, 
          coord.flip = T,
          show.total = F)
```



```{r Bivariado 5, echo=FALSE}
plot_xtab(data_proc$edad_tr, data_proc$confianza,
          title = "Grado de Confianza según Edad",
          show.n = F, 
          coord.flip = T,
          show.total = F)
```

```{r Tabla de Contingencia, echo=FALSE}
sjt.xtab(data_proc$confianza, data_proc$iden_pol, title = "Tabla de Contingencia: Grado confianza según identificacion politica",
         show.col.prc = T, show.row.prc = T)
```

